### ISSUE TITLE
Path.spec.ts test failed!

### ISSUE THREAD

**Issue by tdergouzi** [Uniswap/uniswap-v3-periphery#184]
I changed `tokenAddresses` and `fee`, like this: 
```ts
  let tokenAddresses = [
    '0x5FC8d32690cc91D4c39d9d3abcBD16989F875707',
    '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9',
    '0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9',
    "0x07fF0ed51ABAf0ebeF2dDdabB463A0E17235de46", // Added
  ]
  let fees = [FeeAmount.MEDIUM, FeeAmount.MEDIUM, FeeAmount.MEDIUM]
```
Then i run the test, i got failed: 
```sh
  Path
    ✓ js encoding works as expected
    1) js decoding works as expected
    ✓ gas cost (121ms)
    #hasMultiplePools / #decodeFirstPool / #skipToken / #getFirstPool
      ✓ works on first pool (113ms)
      2) skips 1 item


  3 passing (3s)
  2 failing

  1) Path
       js decoding works as expected:

      AssertionError: expected [ Array(3) ] to deeply equal [ Array(4) ]
      + expected - actual

       [
         "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707"
         "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
         "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
      +  "0x07fF0ed51ABAf0ebeF2dDdabB463A0E17235de46"
       ]
      
      at Context.<anonymous> (test/Path.spec.ts:44:48)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  2) Path
       #hasMultiplePools / #decodeFirstPool / #skipToken / #getFirstPool
         skips 1 item:

      AssertionError: expected true to be false
      + expected - actual

      -true
      +false
      
      at Context.<anonymous> (test/Path.spec.ts:61:72)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)



error Command failed with exit code 2.
```

I think there is some problem about function `decodePath`:
```ts
  while (data.length >= DATA_SIZE) {
    const [[tokenA, tokenB], fee] = decodeOne(data)
    finalToken = tokenB
    tokens = [...tokens, tokenA]
    fees = [...fees, fee]
    data = data.slice((i + 1) * OFFSET) // Should the OFFSET * i ?
    i += 1
  }

**Comment by moodysalem** [comment]
Please send a PR with an additional failing test case if you believe the code is incorrect
